### ISSUE TITLE
Structure Roles More Effectively

### ISSUE THREAD

**Issue by welibekov** [welibekov/grantmaster#2]
We suggest applying the same modularization strategy for role definitions.
By organizing roles into distinct files, we can better manage and understand their dependencies and configurations.

Basic implementation for `fakegres` module.

Here is a example of how role object should look like:
```
- name: "schema_name"
   - schema: "schema_name"
     grants:
       - create
       - select 
```
